name: event-update
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        run: git submodule update --remote
      - name: Commit changes
        run: |
          git config --local user.email "robin_maki@planet.moe"
          git config --local user.name "pjsekai-event-diff-bot"
          git commit -am "Update event data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
